const PDFDocument = require('pdfkit');
const ExcelJS = require('exceljs');
const fs = require('fs');
const path = require('path');
const { Report } = require('../models');

class ReportService {
  async generatePDF(analysisData, datasetName, userId) {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument();
        const fileName = `report-${Date.now()}.pdf`;
        const filePath = path.join('reports', fileName);

        if (!fs.existsSync('reports')) {
          fs.mkdirSync('reports');
        }

        const stream = fs.createWriteStream(filePath);
        doc.pipe(stream);

        // Header
        doc.fontSize(25).text('Techlytics Research Report', { align: 'center' });
        doc.moveDown();
        doc.fontSize(16).text(`Dataset: ${datasetName}`, { align: 'left' });
        doc.text(`Date: ${new Date().toLocaleDateString()}`);
        doc.moveDown();

        // Summary Section
        doc.fontSize(18).text('1. Statistical Summary', { underline: true });
        doc.moveDown(0.5);
        
        const { descriptive } = analysisData;
        for (const field in descriptive) {
          doc.fontSize(12).text(`${this.formatFieldName(field)}:`, { oblique: true });
          doc.text(`  Mean: ${descriptive[field].mean.toFixed(2)}`);
          doc.text(`  Median: ${descriptive[field].median.toFixed(2)}`);
          doc.text(`  Std Dev: ${descriptive[field].stdDev.toFixed(2)}`);
          doc.moveDown(0.5);
        }

        // Research Findings
        doc.moveDown();
        doc.fontSize(18).text('2. Key Research Findings', { underline: true });
        doc.moveDown(0.5);
        analysisData.conclusions.forEach((finding, index) => {
          doc.fontSize(12).text(`${index + 1}. ${finding}`);
        });

        // Footer
        doc.moveDown(2);
        doc.fontSize(10).text('Generated by Techlytics Platform', { align: 'center', color: 'grey' });

        doc.end();

        stream.on('finish', async () => {
          const report = await Report.create({
            user_id: userId,
            report_path: filePath
          });
          resolve(report);
        });
      } catch (error) {
        reject(error);
      }
    });
  }

  async generateExcel(records, datasetName, userId) {
    const workbook = new ExcelJS.Workbook();
    const worksheet = workbook.addWorksheet('Dataset Records');

    worksheet.columns = [
      { header: 'Screen Time', key: 'screen_time', width: 15 },
      { header: 'Social Media', key: 'social_media_usage', width: 15 },
      { header: 'Study Time', key: 'study_time', width: 15 },
      { header: 'Sleep Duration', key: 'sleep_duration', width: 15 },
      { header: 'Device Type', key: 'device_type', width: 15 },
      { header: 'Apps Used', key: 'apps_used', width: 10 },
      { header: 'Productivity Score', key: 'productivity_score', width: 15 }
    ];

    records.forEach(record => {
      worksheet.addRow(record);
    });

    const fileName = `export-${Date.now()}.xlsx`;
    const filePath = path.join('reports', fileName);
    
    if (!fs.existsSync('reports')) {
      fs.mkdirSync('reports');
    }

    await workbook.xlsx.writeFile(filePath);

    const report = await Report.create({
      user_id: userId,
      report_path: filePath
    });

    return report;
  }

  formatFieldName(field) {
    return field.split('_').map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(' ');
  }

  async getUserReports(userId) {
    return await Report.findAll({ where: { user_id: userId }, order: [['generated_at', 'DESC']] });
  }
}

module.exports = new ReportService();
