services:
  backend:
    build:
      target: production
    restart: always
    environment:
      - NODE_ENV=production

  frontend:
    build:
      target: production
    restart: always
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
